export const SET_USER = "SET_USER";
export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const REMOVE_ERRORS = "REMOVE_ERRORS";

export const SELECT_RECIPE = "SELECT_RECIPE";
export const LOADING_RECIPE = "LOADING_RECIPE";
export const STOP_LOADING_RECIPE = "STOP_LOADING_RECIPE";
export const ADD_INGREDIENTS_STEPS = "ADD_INGREDIENTS_STEPS";
export const FROM_LOCAL_UPDATE_STATE = "FROM_LOCAL_UPDATE_STATE";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const LOAD_FAVORITES = "LOAD_FAVORITES";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const LOAD_GROCERIES = "LOAD_GROCERIES";
export const ADD_GROCERY = "ADD_GROCERIES";
export const UPDATE_GROCERY = "UPDATE_GROCERY";
export const REMOVE_GROCERY = "REMOVE_GROCERY";
